# The NumPy Package

## What is it?

NumPy is a Python package used for scientific computing. Often cited as a fundamental package in this area, this is for good reason. It provides a high performance multidimensional array object, and a variety of routines for operations on arrays. NumPy is not part of a basic Python installation. It has to be installed after the Python installation.

The implemented multi-dimensional arrays are very efficient as NumPy was mostly written in C; the precompiled mathematical and numerical functions and functionalities of NumPy guarantee excellent execution speed.

At its core NumPy provides the ndarray (multidimensional/n-dimensional array) object. This is a grid of values of the same type indexed by a tuple of non-negative integers. This is explained in further detail in the basics section below.

## The Basics

In Numpy, axes are called dimensions, lets take a hypothetical set of coordinates and see what exactly this means.

The coordinates of a point in 3D space [1, 4, 5] has one axis that contains 3 elements ie. has a length of 3.
Let's take another example to reinforce this idea.

Using the illustrated graph below we can see that the set of coordinates has 2 axes. Axis 1 has a length (shown in colour) of 2, and axis 2 has a length of 3.

<mark>FIGURE 1</mark>
![Graph displaying axes of coordinate](./images/pointInSpace.jpg)


One of NumPy's most powerful features is it's array class: ```ndarray``` This is not to be confused with the Python's array class ```array.array``` which has less functionality and only handles one-dimensional arrays.

##### Let's use some of ndarray's functions to prove and reinforce what we learnt above.

#### A Simple Example

Before we use NumPy we have to import it.
It is very common to see NumPy renamed to "np".



In [36]:
import numpy as np

From here let's create an array of values that represent distances eg. in metres

In [37]:
mvalues = [45.26, 10.9, 26.3, 80.5, 24.1, 66.1, 19.8, 3.0, 8.8, 132.5]

Great, now let's do some NumPy stuff on that. We're going to turn our array of values into a one-dimensional NumPy array and print it to the screen.

In [38]:
M = np.array(mvalues)
print(M)

[ 45.26  10.9   26.3   80.5   24.1   66.1   19.8    3.     8.8  132.5 ]


Now let's say that we wanted to convert all of our values in metres to centimetres. This is easily achieved using a NumPy array and scalar multiplication.

In [39]:
print(M*100)

[ 4526.  1090.  2630.  8050.  2410.  6610.  1980.   300.   880. 13250.]


If we print out M again you can see that the values have not been changed.

In [40]:
print(M)

[ 45.26  10.9   26.3   80.5   24.1   66.1   19.8    3.     8.8  132.5 ]


Now if you wanted to do the same thing using standard Python, as shown below, then hopefully you can clearly see the advantage in using NumPy instead.

In [41]:
mvalues = [ i*100 for i in mvalues] 
print(mvalues)

[4526.0, 1090.0, 2630.0, 8050.0, 2410.0, 6609.999999999999, 1980.0, 300.0, 880.0000000000001, 13250.0]


The values for mvalues have also all been permanently changed now, whereas we didn't need to alter them when using NumPy 

Earlier I explained that NumPy provides the ndarray object. "M" is an instance of the class ```numpy.ndarray```, proven below:

In [42]:
type(M)

numpy.ndarray

# The NumPy Random Package

In order to use the random package the name of package must be specified followed by the function. 

eg. ```np.random.rand(3,3)``` (It's implied that NumPy has been imported)

## Simple random data
Let's go over some of the functions that NumPy provides to help us deal with simple random data. 

### rand
```rand``` is used to generate random values in a given shape. The dimensions of the input should be positive and if they are not or they're empty a float will be returned. The example below creates an array of specified shape and populates it with random samples from a uniform distribution over [0, 1).

Let's use that example and construct a 2D array of random values. If you wanted a 3D array or greater you would simply add an additional parameter to the function.

In [162]:
np.random.rand(3,3)

array([[0.47745591, 0.51006486, 0.16514169],
       [0.99200483, 0.82997841, 0.71740133],
       [0.23406415, 0.0706828 , 0.3194022 ]])

### randn

```randn``` Returns a sample (or samples) from the “standard normal” distribution.

A standard normal distribution is a normal distribution where the average value is 0, and the variance is 1. 

When the function is provided a positive "int_like or int-convertible arguments", randn generates an array of specified shape (d0, d1, ..., dn), filled with random floats sampled from this distribution. Like ```rand```, a single float is returned if no argument is provided.

In [163]:
np.random.randn(3,2)

array([[-1.61446141, -0.54951317],
       [-0.59537313,  1.92070288],
       [ 0.22518985,  1.0512042 ]])

Additional computations can be added for greater specificity

In [164]:
np.random.randn(3,2) + 8

array([[7.52258729, 5.83368878],
       [8.43516828, 7.26576665],
       [8.38640053, 8.89305758]])

### randint

